/**
 * Local exam import script - run via Claude Code or tsx.
 *
 * Usage:
 *   npx tsx scripts/import-exam.ts "path/to/exam.pdf" "ENARE 2024"
 *
 * Pipeline (API-free for explanations):
 *   1. Parse PDF into questions (structure + alternatives + gabarito if present)
 *   2. Write `data/exams/<slug>.json` with `explicacao: null` for every question
 *   3. Upsert exam + tags + questions into Supabase (explicacao stays null)
 *   4. Extract images and link to questions
 *
 * Explanations are NOT generated by API. Claude (in conversation) authors each
 * one manually: ~150 words, 2 paragraphs — (1) what you need to know to answer,
 * (2) why each other alternative is wrong. Save them back into the JSON and
 * re-run `npm run seed` to sync.
 *
 * Requires SUPABASE_SERVICE_ROLE_KEY in .env.local
 */

import 'dotenv/config';
import fs from 'fs';
import path from 'path';
import { createClient } from '@supabase/supabase-js';

// Load .env.local manually since dotenv/config only loads .env
import dotenv from 'dotenv';
dotenv.config({ path: path.resolve(__dirname, '../.env.local'), override: true });

// Dynamic imports for modules that need env vars at init time
async function loadPdfParser() {
  const mod = await import('../lib/pdf/parser');
  return mod.parsePdf;
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function log(icon: string, msg: string) {
  console.log(`${icon} ${msg}`);
}

async function main() {
  const [pdfPath, examName] = process.argv.slice(2);

  if (!pdfPath || !examName) {
    console.error('Usage: npx tsx scripts/import-exam.ts <pdf-path> <exam-name>');
    console.error('Example: npx tsx scripts/import-exam.ts "provas/ENARE 2024.pdf" "ENARE 2024"');
    process.exit(1);
  }

  if (!fs.existsSync(pdfPath)) {
    console.error(`Arquivo não encontrado: ${pdfPath}`);
    process.exit(1);
  }

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!supabaseUrl || !serviceRoleKey) {
    console.error('NEXT_PUBLIC_SUPABASE_URL e SUPABASE_SERVICE_ROLE_KEY devem estar no .env.local');
    process.exit(1);
  }

  const supabase = createClient(supabaseUrl, serviceRoleKey, {
    auth: { autoRefreshToken: false, persistSession: false },
  });

  // 1. Parse PDF
  log('→', 'Extraindo texto do PDF...');
  const parsePdf = await loadPdfParser();
  const buffer = fs.readFileSync(pdfPath);
  const parsed = await parsePdf(Buffer.from(buffer), examName);

  if (parsed.questoes.length === 0) {
    console.error('Nenhuma questão encontrada no PDF.');
    process.exit(1);
  }

  const questionsWithAnswer = parsed.questoes.filter((q) => q.resposta_correta);
  const questionsWithoutAnswer = parsed.questoes.filter((q) => !q.resposta_correta);
  log('✓', `${parsed.questoes.length} questões encontradas (${questionsWithAnswer.length} com gabarito)`);

  if (questionsWithoutAnswer.length > 0) {
    log('⚠', `${questionsWithoutAnswer.length} questões sem gabarito — preencha resposta_correta no JSON manualmente antes de re-seedar.`);
  }

  // Only import questions that already have a gabarito from the PDF.
  const validQuestions = parsed.questoes.filter((q) => q.resposta_correta);
  if (validQuestions.length === 0) {
    console.error('Nenhuma questão com resposta para importar.');
    process.exit(1);
  }

  // 3. Write canonical JSON to data/exams/<slug>.json (explicacao stays null — Claude fills manually)
  const examSlug = slugify(examName);
  const examsDir = path.resolve(__dirname, '../data/exams');
  if (!fs.existsSync(examsDir)) fs.mkdirSync(examsDir, { recursive: true });
  const jsonPath = path.join(examsDir, `${examSlug}.json`);

  const jsonPayload = {
    prova: examName,
    total_questoes: validQuestions.length,
    questoes: validQuestions.map((q) => ({
      numero: q.numero,
      tags: q.tags,
      enunciado: q.enunciado,
      alternativas: q.alternativas,
      resposta_correta: q.resposta_correta,
      explicacao: null,
    })),
  };

  // Preserve any existing hand-written explanations when re-importing the same exam.
  if (fs.existsSync(jsonPath)) {
    try {
      const existing = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
      const existingByNumero: Record<number, string | null> = {};
      (existing.questoes ?? []).forEach((q: any) => {
        existingByNumero[q.numero] = q.explicacao ?? null;
      });
      jsonPayload.questoes.forEach((q) => {
        if (existingByNumero[q.numero]) q.explicacao = existingByNumero[q.numero] as any;
      });
      log('✓', 'Explicações já existentes preservadas do JSON anterior');
    } catch {
      log('⚠', 'JSON anterior inválido, sobrescrevendo');
    }
  }

  fs.writeFileSync(jsonPath, JSON.stringify(jsonPayload, null, 2), 'utf-8');
  log('✓', `JSON salvo em data/exams/${examSlug}.json`);

  // 4. Create exam record
  log('→', 'Criando registro da prova...');
  const yearMatch = examName.match(/\d{4}/);
  const ano = yearMatch ? parseInt(yearMatch[0]) : new Date().getFullYear();

  const { data: exam, error: examError } = await supabase
    .from('exams')
    .upsert(
      { slug: examSlug, nome: examName, ano, total_questoes: validQuestions.length, is_active: true },
      { onConflict: 'slug' }
    )
    .select()
    .single();

  if (examError) {
    console.error(`Erro ao criar prova: ${examError.message}`);
    process.exit(1);
  }
  log('✓', `Prova "${exam.nome}" (${examSlug})`);

  // 4. Upsert tags
  const uniqueTags = new Set<string>();
  validQuestions.forEach((q) => q.tags.forEach((t) => uniqueTags.add(t)));
  const tagRows = [...uniqueTags].map((nome) => ({ nome, slug: slugify(nome) }));

  let tagLookup: Record<string, string> = {};
  if (tagRows.length > 0) {
    const { data: tags, error: tagsError } = await supabase
      .from('tags')
      .upsert(tagRows, { onConflict: 'nome' })
      .select();
    if (tagsError) {
      console.error(`Erro ao criar tags: ${tagsError.message}`);
      process.exit(1);
    }
    (tags ?? []).forEach((t) => { tagLookup[t.nome] = t.id; });
    log('✓', `${tags?.length ?? 0} tags`);
  }

  // 5. Insert questions
  log('→', 'Inserindo questões...');
  const BATCH_SIZE = 50;
  const insertedQuestions: { id: string; numero: number }[] = [];

  const questionRows = validQuestions.map((q) => ({
    exam_id: exam.id,
    numero: q.numero,
    enunciado: q.enunciado,
    alternativa_a: q.alternativas.A,
    alternativa_b: q.alternativas.B,
    alternativa_c: q.alternativas.C,
    alternativa_d: q.alternativas.D,
    alternativa_e: q.alternativas.E || null,
    resposta_correta: q.resposta_correta,
    explicacao: null,
  }));

  for (let i = 0; i < questionRows.length; i += BATCH_SIZE) {
    const batch = questionRows.slice(i, i + BATCH_SIZE);
    const { data, error } = await supabase
      .from('questions')
      .upsert(batch, { onConflict: 'exam_id,numero' })
      .select('id, numero');
    if (error) {
      console.error(`Erro ao inserir questões (batch ${i}): ${error.message}`);
      process.exit(1);
    }
    insertedQuestions.push(...(data ?? []));
  }
  log('✓', `${insertedQuestions.length} questões inseridas`);

  // 6. Question-tag joins
  const questionLookup: Record<number, string> = {};
  insertedQuestions.forEach((q) => { questionLookup[q.numero] = q.id; });

  const questionTagRows: { question_id: string; tag_id: string }[] = [];
  validQuestions.forEach((q) => {
    const qId = questionLookup[q.numero];
    if (!qId) return;
    q.tags.forEach((tagName) => {
      const tagId = tagLookup[tagName];
      if (tagId) questionTagRows.push({ question_id: qId, tag_id: tagId });
    });
  });

  const questionIdsForExam = insertedQuestions.map((q) => q.id);
  if (questionIdsForExam.length > 0) {
    await supabase.from('question_tags').delete().in('question_id', questionIdsForExam);
  }
  for (let i = 0; i < questionTagRows.length; i += BATCH_SIZE) {
    const batch = questionTagRows.slice(i, i + BATCH_SIZE);
    await supabase.from('question_tags').insert(batch);
  }
  log('✓', `${questionTagRows.length} tag-links`);

  // 7. Extract content images from PDF (skip watermarks automatically)
  log('→', 'Extraindo imagens do PDF...');
  try {
    const { extractPdfImages } = await import('../lib/pdf/image-extractor');
    const images = await extractPdfImages(buffer, examSlug);

    if (images.length > 0) {
      let imageCount = 0;
      for (let i = 0; i < images.length; i++) {
        const img = images[i];
        const questionId = questionLookup[img.questionNumber];
        if (!questionId) continue;

        const { error } = await supabase.from('question_images').upsert({
          question_id: questionId,
          image_url: img.imageUrl,
          image_type: 'figure',
          display_order: i,
          page_number: img.pageNumber,
        }, { onConflict: 'question_id,image_url', ignoreDuplicates: true });

        if (!error) imageCount++;
      }
      log('✓', `${imageCount} imagens vinculadas a questões (${images.length} extraídas, marcas d'água ignoradas)`);
    } else {
      log('✓', 'Nenhuma imagem de conteúdo encontrada no PDF');
    }
  } catch (err: any) {
    log('⚠', `Erro ao extrair imagens: ${err.message}. Continuando sem imagens.`);
  }

  // 8. Push any hand-written explanations already present in the JSON into Supabase
  const withExplicacao = jsonPayload.questoes.filter((q) => q.explicacao);
  if (withExplicacao.length > 0) {
    log('→', `Sincronizando ${withExplicacao.length} explicações manuais do JSON...`);
    for (const q of withExplicacao) {
      const qId = questionLookup[q.numero];
      if (!qId) continue;
      await supabase.from('questions').update({ explicacao: q.explicacao }).eq('id', qId);
    }
    log('✓', 'Explicações sincronizadas');
  }

  const missing = jsonPayload.questoes.filter((q) => !q.explicacao).length;
  if (missing > 0) {
    log('📝', `${missing} questões ainda sem explicação. Escreva manualmente em data/exams/${examSlug}.json e rode "npm run seed".`);
  }

  log('🎉', `Importação concluída! Prova: /exam/${examSlug}`);
}

main().catch((err) => {
  console.error('Erro fatal:', err);
  process.exit(1);
});
